[project]
name = "samples"
version = "0.1.0"
requires-python = ">= 3.8"
dependencies = [
    "requests>=2.32.3",
    "pyzipper>=0.3.6",
]

[tool.rye]
managed = true
virtual = true

[tool.rye.workspace]
